### ISSUE TITLE
`-resume` executing already done processes

### ISSUE THREAD

**Issue by effidotpy** [effidotpy/mito-variant-calling#13]
After a few executions with the `-resume` parameter I have noticed that, sometimes, already finished jobs are launched again. With this being not ideal at all, it is even worst at process such as `MERGE_BAMS` and `MERGE_VCFS` which directly fail.

Example:

```
(base) dani@toshiba:~/effidotpy/mito-variant-calling$ nextflow run main.nf -with-docker mapping_gatk -resume
N E X T F L O W  ~  version 23.10.1
Launching `main.nf` [mad_euler] DSL2 - revision: 60ac87cd16
executor >  local (4)
[ef/0809c9] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:ADD_READGROUP (1)     [100%] 2 of 2, cached: 2 ✔
[15/576e33] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:NAME_SORT (2)         [100%] 2 of 2, cached: 2 ✔
[82/9ea4f5] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:FIX_PAIRING (2)       [100%] 2 of 2, cached: 2 ✔
[b3/4291a7] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:REMOVE_SINGLETONS (2) [100%] 2 of 2, cached: 2 ✔
[d5/0f68bb] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:REVERT_BAM (1)        [100%] 2 of 2, cached: 2 ✔
[ed/71945b] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:BAM_TO_FASTQ (1)      [100%] 2 of 2, cached: 2 ✔
[d5/7c978d] process > MITO_SNVS_INDELS:ALIGN_TO_REF:ALIGN_BWA (2)              [100%] 2 of 2, cached: 2 ✔
[c1/1823ce] process > MITO_SNVS_INDELS:ALIGN_TO_REF:MERGE_BAMS (2)             [  0%] 0 of 2
[-        ] process > MITO_SNVS_INDELS:ALIGN_TO_REF:SORT_BAM                   -
[ae/3fd984] process > MITO_SNVS_INDELS:ALIGN_TO_SHIFT:ALIGN_BWA (2)            [100%] 2 of 2, cached: 2 ✔
[d7/be82d2] process > MITO_SNVS_INDELS:ALIGN_TO_SHIFT:MERGE_BAMS (2)           [  0%] 0 of 2
[-        ] process > MITO_SNVS_INDELS:ALIGN_TO_SHIFT:SORT_BAM                 -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:VAR_CALLING             -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:VAR_CALLING_SHIFT       -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:LIFTOVER                -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:MERGE_VCFS              -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:MERGE_STATS             -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:FILTER_MUTECT           -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:BLACKLIST_SITES         -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:NORMALIZE_CALLS         -
[-        ] process > MITO_SNVS_INDELS:ANNOTATION:VARNOTE                      -
[-        ] process > MITO_SNVS_INDELS:ANNOTATION:HAPLOCHECK                   -
[-        ] process > MITO_SNVS_INDELS:ANNOTATION:HAPLOGREP                    -
ERROR ~ Error executing process > 'MITO_SNVS_INDELS:ALIGN_TO_SHIFT:MERGE_BAMS (2)'

Caused by:
  Process `MITO_SNVS_INDELS:ALIGN_TO_SHIFT:MERGE_BAMS (2)` terminated with an error exit status (1)

Command executed:

  java -jar /app/picard.jar MergeBamAlignment -UNMAPPED revert.bam -ALIGNED aligned.bam -R /references/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta \
  -O merged.bam --ATTRIBUTES_TO_RETAIN "X0" --ATTRIBUTES_TO_REMOVE NM --ATTRIBUTES_TO_REMOVE MD

Command exit status:
  1

Command output:
  (empty)
executor >  local (4)
[ef/0809c9] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:ADD_READGROUP (1)     [100%] 2 of 2, cached: 2 ✔
[15/576e33] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:NAME_SORT (2)         [100%] 2 of 2, cached: 2 ✔
[82/9ea4f5] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:FIX_PAIRING (2)       [100%] 2 of 2, cached: 2 ✔
[b3/4291a7] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:REMOVE_SINGLETONS (2) [100%] 2 of 2, cached: 2 ✔
[d5/0f68bb] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:REVERT_BAM (1)        [100%] 2 of 2, cached: 2 ✔
[ed/71945b] process > MITO_SNVS_INDELS:PROCESS_INPUT_BAM:BAM_TO_FASTQ (1)      [100%] 2 of 2, cached: 2 ✔
[d5/7c978d] process > MITO_SNVS_INDELS:ALIGN_TO_REF:ALIGN_BWA (2)              [100%] 2 of 2, cached: 2 ✔
[c1/1823ce] process > MITO_SNVS_INDELS:ALIGN_TO_REF:MERGE_BAMS (2)             [  0%] 0 of 2
[-        ] process > MITO_SNVS_INDELS:ALIGN_TO_REF:SORT_BAM                   -
[ae/3fd984] process > MITO_SNVS_INDELS:ALIGN_TO_SHIFT:ALIGN_BWA (2)            [100%] 2 of 2, cached: 2 ✔
[d7/be82d2] process > MITO_SNVS_INDELS:ALIGN_TO_SHIFT:MERGE_BAMS (2)           [ 50%] 1 of 2, failed: 1
[-        ] process > MITO_SNVS_INDELS:ALIGN_TO_SHIFT:SORT_BAM                 -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:VAR_CALLING             -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:VAR_CALLING_SHIFT       -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:LIFTOVER                -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:MERGE_VCFS              -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:MERGE_STATS             -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:FILTER_MUTECT           -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:BLACKLIST_SITES         -
[-        ] process > MITO_SNVS_INDELS:VARIANT_CALLING:NORMALIZE_CALLS         -
[-        ] process > MITO_SNVS_INDELS:ANNOTATION:VARNOTE                      -
[-        ] process > MITO_SNVS_INDELS:ANNOTATION:HAPLOCHECK                   -
[-        ] process > MITO_SNVS_INDELS:ANNOTATION:HAPLOGREP                    -
ERROR ~ Error executing process > 'MITO_SNVS_INDELS:ALIGN_TO_SHIFT:MERGE_BAMS (2)'

Caused by:
  Process `MITO_SNVS_INDELS:ALIGN_TO_SHIFT:MERGE_BAMS (2)` terminated with an error exit status (1)

Command executed:

  java -jar /app/picard.jar MergeBamAlignment -UNMAPPED revert.bam -ALIGNED aligned.bam -R /references/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta \
  -O merged.bam --ATTRIBUTES_TO_RETAIN "X0" --ATTRIBUTES_TO_REMOVE NM --ATTRIBUTES_TO_REMOVE MD

Command exit status:
  1

Command output:
  (empty)

Command error:
  Mar 28, 2024 11:37:59 AM com.intel.gkl.NativeLibraryLoader load
  INFO: Loading libgkl_compression.so from jar:file:/app/picard.jar!/com/intel/gkl/native/libgkl_compression.so
  [Thu Mar 28 11:37:59 GMT 2024] MergeBamAlignment --UNMAPPED_BAM revert.bam --ALIGNED_BAM aligned.bam --OUTPUT merged.bam --ATTRIBUTES_TO_RETAIN X0 --ATTRIBUTES_TO_REMOVE NM --ATTRIBUTES_TO_REMOVE MD --REFERENCE_SEQUENCE /references/Homo_sapiens_assembly38.chrM.shifted_by_8000_bases.fasta --ADD_PG_TAG_TO_READS true --PAIRED_RUN true --CLIP_ADAPTERS true --IS_BISULFITE_SEQUENCE false --ALIGNED_READS_ONLY false --MAX_INSERTIONS_OR_DELETIONS 1 --ATTRIBUTES_TO_REVERSE OQ --ATTRIBUTES_TO_REVERSE U2 --ATTRIBUTES_TO_REVERSE_COMPLEMENT E2 --ATTRIBUTES_TO_REVERSE_COMPLEMENT SQ --READ1_TRIM 0 --READ2_TRIM 0 --ALIGNER_PROPER_PAIR_FLAGS false --SORT_ORDER coordinate --PRIMARY_ALIGNMENT_STRATEGY BestMapq --CLIP_OVERLAPPING_READS true --HARD_CLIP_OVERLAPPING_READS false --INCLUDE_SECONDARY_ALIGNMENTS true --ADD_MATE_CIGAR true --UNMAP_CONTAMINANT_READS false --MIN_UNCLIPPED_BASES 32 --MATCHING_DICTIONARY_TAGS M5 --MATCHING_DICTIONARY_TAGS LN --UNMAPPED_READ_STRATEGY DO_NOT_CHANGE --VERBOSITY INFO --QUIET false --VALIDATION_STRINGENCY STRICT --COMPRESSION_LEVEL 5 --MAX_RECORDS_IN_RAM 500000 --CREATE_INDEX false --CREATE_MD5_FILE false --help false --version false --showHidden false --USE_JDK_DEFLATER false --USE_JDK_INFLATER false
  [Thu Mar 28 11:38:00 GMT 2024] Executing as root@dcad1c8db4be on Linux 5.15.0-101-generic amd64; OpenJDK 64-Bit Server VM 17.0.9+9-Ubuntu-122.04; Deflater: Intel; Inflater: Intel; Provider GCS is available; Picard version: Version:3.1.1
  INFO	2024-03-28 11:38:00	SamAlignmentMerger	Processing SAM file(s): [aligned.bam]
  WARNING	2024-03-28 11:38:00	SamAlignmentMerger	Exception merging bam alignment - attempting to sort aligned reads and try again: Aligned record iterator (V350159019L1C001R00100059450) is behind the unmapped reads (V350159019L1C001R00100070732)
  INFO	2024-03-28 11:38:03	SamAlignmentMerger	Finished reading 85968 total records from alignment SAM/BAM.
  [Thu Mar 28 11:38:03 GMT 2024] picard.sam.MergeBamAlignment done. Elapsed time: 0.07 minutes.
  Runtime.totalMemory()=392167424
  To get help, see http://broadinstitute.github.io/picard/index.html#GettingHelp
  Exception in thread "main" java.lang.IllegalStateException: Aligned record iterator (V350159019L1C001R00100059450) is behind the unmapped reads (V350159019L1C001R00100070732)
  	at picard.sam.AbstractAlignmentMerger.mergeAlignment(AbstractAlignmentMerger.java:557)
  	at picard.sam.SamAlignmentMerger.mergeAlignment(SamAlignmentMerger.java:186)
  	at picard.sam.MergeBamAlignment.doWork(MergeBamAlignment.java:368)
  	at picard.cmdline.CommandLineProgram.instanceMain(CommandLineProgram.java:280)
  	at picard.cmdline.PicardCommandLine.instanceMain(PicardCommandLine.java:105)
  	at picard.cmdline.PicardCommandLine.main(PicardCommandLine.java:115)

Work dir:
  /home/dani/effidotpy/mito-variant-calling/work/d7/be82d2ceb1dff882939bd39018cc04

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '.nextflow.log' file for details

```

**Comment by effidotpy** [comment]
Check this issue https://github.com/nextflow-io/nextflow/issues/1629

**Comment by effidotpy** [comment]
The reason is described in the **Non-deterministic input channels** section of [troubleshooting-nextflow-resume](https://www.nextflow.io/blog/2019/troubleshooting-nextflow-resume.html). I solve it by using `join()` with `val(metaMap)` as the key.
